PreMiD/Discord-Bot

src/events/message.js, src/messageFiltered.json
I wish I could help more than that but I have my site to take care of, sorry.
love u guys.
=> Message Filtering

src/events/message.js, src/messageFiltered.json
=> i forget discord.js sorry

src/commands/mute.js, src/commands/unmute.js, src/events/message.js
Okay, I'm getting addicted to doing PR :relaxed: :flushed: 
Suggestion: 
Leave moderator and Jr. moderador roles mentionable so they will be notified in the logs.
=> Mute / Unmute commands and Message filtering improvement

src/commands/unmute.js
=> My last PR

src/commands/mute.js, src/commands/unmute.js, src/config.json, src/events/guildMemberAdd.js, src/events/message.js, src/messageFiltered.json
thanks to @frozaum and @DooML for the help with tests
=> Naked bot detection and refactoring message filter

README.md, src/modules/credits/index.ts
=> Best changes ever made.

src/index.ts, src/modules/moderation/commands/info.ts, src/modules/moderation/short-infos.json, src/util/moduleLoader.ts
Isn't this a great idea? Check the code and make sure it works before merging it, because I didn't check it yknow :^) Fuck TS :^)
=> What if this or something like this was a thing?

src/modules/moderation/short-infos.json
=> very big fix.

src/modules/credits/creditRoles.json
wow, took my time to order them.
=> Added new roles, ordered and added role names so no confusion.

package.json, src/modules/credits/index.ts, yarn.lock
croooooooooooooooooooooooooooooooooooooooooon
runs every 3rd hour
=> fix credits so they don't lag bot

src/index.ts
=> Status Fix

src/messageFiltered.ts, src/modules/status/index.ts
Adds the following things:
- Status checker, which makes requests to the status page API and posts updates on the status to the Discord server's #updates channel.
- Small style change in the filter configuration
=> Status checker + style update

src/modules/moderation/short-infos.ts, src/modules/support/events/message.ts, src/modules/utility/commands/ping.ts
https://share.clickup.com/v/4-3922623-1/t/50jcv4/p-close-in-ticket-channels-causes-an-unknown-channel-exception-probably-because-it-tries-sending-the-join-msg
=> Fixed ping command, fixed unhandled channel exception.

src/modules/assign/assignee.ts, src/modules/assign/commands/assign.ts, src/modules/assign/staffassign.ts
As per request of fellow staff, this command was edited.
=> Fixing Task ID: CU-5wq42d

src/modules/moderation/commands/warns.ts
Adding checking to try and dm, if there is an error then it will send it to the channel.
=> Redoing Task ID: CU-7wc34z

src/modules/utility/commands/ping.ts
Reversed red/green - fixed
Orange is now orange not yellow
=> Color fixes

src/modules/utility/commands/search.ts
Re coded it so now it uses an regex for searching for:
> Name
> Service
> Url
> Tags
[Image of the bot working](https://cdn.pxseu.cc/gWtmmL99m.png)
=> Fixed search command

src/config.ts, src/modules/assign/assignRoles.ts, src/modules/assign/assignee.ts, src/modules/assign/commands/assign.ts, src/modules/assign/commands/unassign.ts, src/modules/assign/staffassign.ts, src/modules/utility/commands/usage.ts
Assign Vacation Role, Minecraft Role, Linux Tester role are done.
With this I also add the Preansce usage commannd.
=> Tasks from To Do

src/modules/assign/commands/assign.ts, src/modules/assign/commands/unassign.ts, src/modules/utility/commands/usage.ts
Fixed my major spelling inability,
Minor improvement  for searching
ps Sorry for the miss spelling :sob:
=> Minor fixes

src/modules/assign/assignRoles.ts, src/modules/assign/assignee.ts, src/modules/assign/commands/assign.ts, src/modules/assign/commands/unassign.ts, src/modules/moderation/commands/info.ts, src/modules/moderation/short-infos.ts
-Info command updates,
-Fixes to my trash stuff
=> Recent work

src/modules/assign/commands/assign.ts, src/modules/assign/commands/unassign.ts
fix for the assign embed not deleting itself
also my "small" mistake (assign roles auto adding minecraft ((again)))
=> fix for the assign embed not deleting itself

src/modules/credits/index.ts, src/modules/support/classes/Ticket.ts
Uses env variable with ALL CAPS because of.. "rules".
=> 💊 ALL CAPS!!!

src/modules/moderation/commands/info.ts, src/modules/moderation/short-infos.ts, src/modules/utility/index.ts
This makes it so the data on the DB is always up to date with the most recent information obtained from Crowdin every minute and isn't stuck on the response we get when the user verifies.
=> Update the user object with Crowdin data

src/modules/moderation/short-infos.ts
- Fixes the issue with the duplicated "donate" alias
=> 🐛 Fixes Duplicated Aliases 

src/database/client.ts, src/modules/credits/index.ts, src/modules/credits/roleColor.ts
Updates DB connection environment variables
Delete all Mongo env vars and replace with `MongoURl = Full_connection_string`
=> Fix roleColor for credits

package.json, yarn.lock
Reverts PreMiD/Discord-Bot#578
=> Revert "🔼 Bump chalk from 4.1.2 to 5.0.0"

.prettierrc, @types/djs-extender.d.ts, README.md, src/events/guildMemberAdd.ts, src/events/guildMemberRemove.ts, src/events/ready.ts, src/index.ts, src/modules/betaAlpha/events/guildMemberUpdate.ts, src/modules/betaAlpha/index.ts, src/modules/credits/index.ts, src/modules/utility/commands/info.ts, src/modules/utility/commands/presences.ts, src/util/classes/Module.ts, src/util/classes/ModuleLoader.ts, tsconfig.json
This pull request:
- Adds a randomly changing presence with the proper types, I can change the interval if needed 
- Removes the `footer` property on info command as it is never removed
- Adds Prettier with the same config as PreMiD/Presences
=> feat: add random status, add prettier & remove footer on info command

src/modules/utility/commands/info.ts
- write of info commands to improve english, grammar and consistency
- removed crowdinStringIssue as it is on the Localisation bot - approved by Rodry
- added frequentFixes to aid support agents
=> style(info): rewrite info commands

pnpm-lock.yaml, src/modules/utility/commands/info.ts
Made a simple command for info about the beta
=> feat: add beta command
